/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/kimba74/sandbox-k8s-controller/pkg/apis/soabridge.com/v1alpha1"
	scheme "github.com/kimba74/sandbox-k8s-controller/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// SamplersGetter has a method to return a SamplerInterface.
// A group's client should implement this interface.
type SamplersGetter interface {
	Samplers(namespace string) SamplerInterface
}

// SamplerInterface has methods to work with Sampler resources.
type SamplerInterface interface {
	Create(*v1alpha1.Sampler) (*v1alpha1.Sampler, error)
	Update(*v1alpha1.Sampler) (*v1alpha1.Sampler, error)
	UpdateStatus(*v1alpha1.Sampler) (*v1alpha1.Sampler, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.Sampler, error)
	List(opts v1.ListOptions) (*v1alpha1.SamplerList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Sampler, err error)
	SamplerExpansion
}

// samplers implements SamplerInterface
type samplers struct {
	client rest.Interface
	ns     string
}

// newSamplers returns a Samplers
func newSamplers(c *SoabridgeV1alpha1Client, namespace string) *samplers {
	return &samplers{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the sampler, and returns the corresponding sampler object, and an error if there is any.
func (c *samplers) Get(name string, options v1.GetOptions) (result *v1alpha1.Sampler, err error) {
	result = &v1alpha1.Sampler{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("samplers").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Samplers that match those selectors.
func (c *samplers) List(opts v1.ListOptions) (result *v1alpha1.SamplerList, err error) {
	result = &v1alpha1.SamplerList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("samplers").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested samplers.
func (c *samplers) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("samplers").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a sampler and creates it.  Returns the server's representation of the sampler, and an error, if there is any.
func (c *samplers) Create(sampler *v1alpha1.Sampler) (result *v1alpha1.Sampler, err error) {
	result = &v1alpha1.Sampler{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("samplers").
		Body(sampler).
		Do().
		Into(result)
	return
}

// Update takes the representation of a sampler and updates it. Returns the server's representation of the sampler, and an error, if there is any.
func (c *samplers) Update(sampler *v1alpha1.Sampler) (result *v1alpha1.Sampler, err error) {
	result = &v1alpha1.Sampler{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("samplers").
		Name(sampler.Name).
		Body(sampler).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *samplers) UpdateStatus(sampler *v1alpha1.Sampler) (result *v1alpha1.Sampler, err error) {
	result = &v1alpha1.Sampler{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("samplers").
		Name(sampler.Name).
		SubResource("status").
		Body(sampler).
		Do().
		Into(result)
	return
}

// Delete takes name of the sampler and deletes it. Returns an error if one occurs.
func (c *samplers) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("samplers").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *samplers) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("samplers").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched sampler.
func (c *samplers) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Sampler, err error) {
	result = &v1alpha1.Sampler{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("samplers").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
