/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	time "time"

	soabridge_com_v1alpha1 "github.com/kimba74/sandbox-k8s-controller/pkg/apis/soabridge.com/v1alpha1"
	versioned "github.com/kimba74/sandbox-k8s-controller/pkg/client/clientset/versioned"
	internalinterfaces "github.com/kimba74/sandbox-k8s-controller/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/kimba74/sandbox-k8s-controller/pkg/client/listers/soabridge.com/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// SamplerInformer provides access to a shared informer and lister for
// Samplers.
type SamplerInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.SamplerLister
}

type samplerInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewSamplerInformer constructs a new informer for Sampler type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewSamplerInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredSamplerInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredSamplerInformer constructs a new informer for Sampler type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredSamplerInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.SoabridgeV1alpha1().Samplers(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.SoabridgeV1alpha1().Samplers(namespace).Watch(options)
			},
		},
		&soabridge_com_v1alpha1.Sampler{},
		resyncPeriod,
		indexers,
	)
}

func (f *samplerInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredSamplerInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *samplerInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&soabridge_com_v1alpha1.Sampler{}, f.defaultInformer)
}

func (f *samplerInformer) Lister() v1alpha1.SamplerLister {
	return v1alpha1.NewSamplerLister(f.Informer().GetIndexer())
}
